CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_POINTING=y
CONFIG_LPPS=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
C# ポインティング全体の処理ループを 5ms（200Hz）間隔に高速化
CONFIG_ZMK_POINTING_TICK_DURATION=5
# マウス・ポインティング入力のバッファ・応答性を最適化（対応している環境用）
CONFIG_ZMK_POINTING_FPS=125
